<?php

/**
 * @file
 * A module that contains code to be tested for Twig's entity_embed().
 */

/**
 * Implements hook_theme().
 */
function entity_embed_twig_test_theme($existing, $type, $theme, $path) {
  $items['entity_embed_twig_test'] = array(
    'template' => 'entity_embed_twig_test',
    'variables' => array(
      'entity_type' => '',
      'id' => '',
      'display_plugin' => 'default',
      'display_settings' => array(),
    ),
  );
  return $items;
}
